### ISSUE TITLE
Triggers do not load properly on server startup 

### ISSUE THREAD

**Issue by Leomelonseeds** [Pwing-Minecraft/PwingRaces-Plugin#3]
Hello,

As indicated by the title, triggers will not work on initial server start, and requires /race reload to function properly.

This was tested with a race that gave potion effects as a trigger. No potion effects were given when I joined the server after it started up until I used /race reload.

Thanks for your time.

**Comment by RednedEpic** [comment]
This has been fixed in the latest build.
